---
abstract: 'Just roles. Nothing else.'
author:
  - "Curtis 'Ovid' Poe <ovid@cpan.org>"
build_requires:
  Test::Most: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Role-Basic
provides:
  Role::Basic:
    file: lib/Role/Basic.pm
    version: 0.02
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
